version: "3"
services:
  todo-redux-dev:
    container_name: todo-react
    image: todo-frontend:1.0
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    env_file:
      - .env
