version: "3"
services:
  todo-redux-dev:
    container_name: todo-react
    image: todo-frontend:1.0
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - .env
    # environment:
    #   - REACT_APP_API_BASE_URL=https://65cb1018efec34d9ed86a4f4.mockapi.io/api/v1
    #   - REACT_APP_API_TODOS_ENDPOINT=todos
    volumes:
      - ./src:/app/src
