FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
# ENV REACT_APP_API_BASE_URL=https://65cb1018efec34d9ed86a4f4.mockapi.io/api/v1
# ENV REACT_APP_API_TODOS_ENDPOINT=todos
CMD ["npm", "start"]
