version: "3"
services:
  reverse-proxy:
    image: traefik:v2.11
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  todo-redux-dev:
    container_name: todo-react
    image: todo-frontend:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    labels:
      - traefik.http.routers.todo-redux-dev.rule=Host(`chiragboghara.localhost`)
